//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Martin Granell, Readify
// 
//      It contains classes defined from the contents of the resource file:
//        E:\Work\SEM\Excel_Client\src\Ganji.ExcelManagement\SR.srt.resx
// 
//      Generated: Thursday, July 07, 2011 10:31 AM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Common.Excel.Management
{
    
    
    /// <summary>
    /// </summary>
    internal partial class SR
    {
        
        /// <summary>
        /// </summary>
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return Keys_SR.Culture;
            }
            set
            {
                Keys_SR.Culture = value;
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string AutoEstimateBid_Sheet_Button_Text
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.AutoEstimateBid_Sheet_Button_Text);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string Close_Sheet_Button_Text
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.Close_Sheet_Button_Text);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string ExcelError_FailedToCreateNewSheet
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.ExcelError_FailedToCreateNewSheet);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string Import_Add_Tracking_Text
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.Import_Add_Tracking_Text);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string Import_Sheet_Button_Text
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.Import_Sheet_Button_Text);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string Import_Validate_Sheet_Button_Text
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.Import_Validate_Sheet_Button_Text);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string ImportAdd_Sheet_Button_Text
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.ImportAdd_Sheet_Button_Text);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string SelectRange_Dialog_Label
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.SelectRange_Dialog_Label);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string SelectRange_Dialog_Title
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.SelectRange_Dialog_Title);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string Update_Sheet_Button_Text
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.Update_Sheet_Button_Text);
            }
        }
        
        /// <summary>
        /// </summary>
        internal class Keys_SR
        {
            
            /// <summary>
            /// </summary>
            internal static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Common.Excel.Management.SR.srt", typeof(Common.Excel.Management.SR).Assembly);
            
            /// <summary>
            /// </summary>
            static System.Globalization.CultureInfo _culture = null;
            
            /// <summary>
            /// </summary>
            internal const string AutoEstimateBid_Sheet_Button_Text = "AutoEstimateBid_Sheet_Button_Text";
            
            /// <summary>
            /// </summary>
            internal const string Close_Sheet_Button_Text = "Close_Sheet_Button_Text";
            
            /// <summary>
            /// </summary>
            internal const string ExcelError_FailedToCreateNewSheet = "ExcelError_FailedToCreateNewSheet";
            
            /// <summary>
            /// </summary>
            internal const string Import_Add_Tracking_Text = "Import_Add_Tracking_Text";
            
            /// <summary>
            /// </summary>
            internal const string Import_Sheet_Button_Text = "Import_Sheet_Button_Text";
            
            /// <summary>
            /// </summary>
            internal const string Import_Validate_Sheet_Button_Text = "Import_Validate_Sheet_Button_Text";
            
            /// <summary>
            /// </summary>
            internal const string ImportAdd_Sheet_Button_Text = "ImportAdd_Sheet_Button_Text";
            
            /// <summary>
            /// </summary>
            internal const string SelectRange_Dialog_Label = "SelectRange_Dialog_Label";
            
            /// <summary>
            /// </summary>
            internal const string SelectRange_Dialog_Title = "SelectRange_Dialog_Title";
            
            /// <summary>
            /// </summary>
            internal const string Update_Sheet_Button_Text = "Update_Sheet_Button_Text";
            
            /// <summary>
            /// </summary>
            internal static System.Globalization.CultureInfo Culture
            {
                get
                {
                    return _culture;
                }
                set
                {
                    _culture = value;
                }
            }
            
            /// <summary>
            /// </summary>
            internal static string GetString(string key)
            {
                return resourceManager.GetString(key, _culture);
            }
            
            /// <summary>
            /// </summary>
            internal static string GetString(string key, object[] args)
            {
                string msg = resourceManager.GetString(key, _culture);
                msg = string.Format(msg, args);
                return msg;
            }
        }
    }
}
